# Generated by Django 5.1.1 on 2024-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("author", models.CharField(max_length=264)),
                ("published_at", models.DateTimeField()),
                ("content", models.TextField()),
                ("url", models.URLField(unique=True)),
                ("tags", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_at"],
            },
        ),
    ]
